### Конспект статьи по numpy из stanford cs231

Numpy - основная библиотека для научных вычислений в python. Она предоставляет высокок производительные многомерные массивы, и инструменты для работы с ними.

## Arrays
- В numpy массивы это сетка значений одного типа, индексируемая кортежем неотрицательных чисел.
- Колличество измерений - ранг массива
- Форма (shape) массива - кортеж целых чисел, дающих инфомацию о размере массива вдоль каждого из измерений.

In [ ]:
import numpy as np

# массив можно создать из python списка
a = np.array([1, 2, 3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [32]:
# numpy также предоставляет много иных функций создания массива
a = np.zeros((2, 2))
print(a)

b = np.ones([3, 2, 4]) # тензор 3 слоя высотой 2 шириной 4
print(b)

c = np.full((2, 2), 67)
print(c)

d = np.eye(2) # I \in R^2
print(d)

e = np.random.random((2, 2))
print(e)

[[0. 0.]
 [0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[67 67]
 [67 67]]
[[1. 0.]
 [0. 1.]]
[[0.50769019 0.42794261]
 [0.87807058 0.88088431]]


### Array indexing
**Slicing**: идентично питоновским листам. Если массив многомерный, то слайсим каждое измерение

In [44]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

b = a[:2, 1:3]
print(b)

# слайс это предстваление исходных данных, то есть если его отредактировать , то и исходное отредактируется

b[0, 0] = 77
print(a[0, 1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
77


In [ ]:
# можно смешивать индексирование целочимсленное и посредством срезов
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Смешивание целочисленной индексации со срезами дает массив более низкого ранга,
# Использование только срезов дает массив того же ранга
row_r1 = a[1, :] # rank 1
row_r2 = a[1:2, :] # rank 2
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [55]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
print(a[[0, 1, 2], [0, 1, 0]]) # [индексы строк], [индексы столбцов]

print(a[[0, 0], [1, 1]])  # Prints "[2 2]"
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[2 2]
[2 2]


Полезным трюком с индексированием массивов является выбор или из менение одного элемента из каждого стобца

In [65]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

b = np.array([0, 2, 0, 1]) # индекты

print(a[np.arange(4), b]) # из каждой строки получаем, элементы согласно b
a[np.arange(4), b] += 10

print(a)

[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


**Boolean array indexing:** позволяет выбрать некие поизвольные элементы из массива, обычно  удовл. условию.

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)
bool_idx

print(a[bool_idx]) # rank = 1

print(a[(a > 2)]) # a[bool_idx]

[3 4 5 6]


### Datatypes
Типы данных примерно как в С. 
```python
x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"
```

### Array math
основные математические операции доступны, как посредством функций, так и перегруженных операций 

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x + y)
print(np.add(x, y), "\n")

print(x - y)
print(np.subtract(x, y), "\n")

print(x * y) # не матричное произведение
print(np.multiply(x, y), "\n")

print(x / y)
print(np.divide(x, y), "\n")

print(np.sqrt(x))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]] 

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]] 

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]] 

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]] 

[[1.         1.41421356]
 [1.73205081 2.        ]]


Для **матричного произведения** - используем функию или метод `dot`

In [75]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9, 10])
w = np.array([11, 12])

# вектор на вектор
print(v.dot(w))
print(np.dot(v, w))

# матрица на векотр
print(x.dot(v))
print(np.dot(x, v))

# матрица на матрицу
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


В numpy есть функции, позволяющие проводить вычислительные операции на массивах

In [79]:
x = np.array([[1, 2], [3, 4]])

print(np.sum(x))  # prints "10"
print(np.sum(x, axis=0))  # для каждой колонки "[4 6]"
print(np.sum(x, axis=1))  # для кадого стобца "[3 7]"

10
[4 6]
[3 7]


In [ ]:
x = np.array([[1, 2], [3, 4]])
print(x.T)

# трансопнированой от ранга 1 не существует
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 3]
 [2 4]]


## Broadcasting
Механизм NumPy, который позволяет выполнять операции с массивами разного размера без явного дублирования данных.

Когда NumPy выполняет арифметические операции между массивами разных размеров, он автоматически расширяет (broadcasts) меньший массив так, чтобы их формы совпадали

In [ ]:
# без бродкастинга
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv, '\n')

y = x + vv
print(y)


[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]] 

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [90]:
# с бродкастингом

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12],])
v = np.array([1, 0, 1])
y = x + v
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

**Правила broadcasting в NumPy:**
- **Выравнивание размерностей:**
Если у массивов разное число осей, добавляем 1 к форме меньшего массива слева, пока их размерности не совпадут.

- **Совместимость размерностей:**
Два массива считаются совместимыми по оси, если:
их размеры совпадают, или
один из них имеет размер 1 (он будет расширен).

- **Общее правило:**
Broadcasting возможен, если массивы совместимы по всем осям.

- **Финальная форма:**
После broadcasting массивы ведут себя так, как если бы у них была форма max(shape1, shape2) по каждой оси.

- **Копирование вдоль оси:**
Если в какой-то оси один массив имеет размер 1, он дублируется до нужного размера.

**ПРИМЕР:**

In [96]:
v = np.array([1,2,3])  # (3,)
w = np.array([4,5])    # (2,)

# чтобы вычлить внешнее прозведение, преоразуем v в (1,3)

print(np.reshape(v, (3, 1)) * w)

# Прибавление вектора к каждой строке матрицы
x = np.array([[1,2,3], [4,5,6]])  # (2,3)
print(x + v)

# Прибавление вектора к каждому столбцу матрицы
print((x.T + w).T)
print(x + np.reshape(w, (2, 1)))


[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]


Broadcasting делает код более лаконичным и быстрым, поэтому стоит использовать его, где возможно.

**SciPy** — библиотека для научных вычислений, постоенная поверх numpy, предлагающая функции для: линала, статистики, оптимизации и т.д.
